FROM --platform=$BUILDPLATFORM golang:1.26 AS builder

ARG TARGETOS
ARG TARGETARCH
ARG VERSION=dev/unknown

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH \
    go build -ldflags "-s -w -X main.version=${VERSION}" -trimpath -o /mosdns .

FROM alpine:latest

RUN apk add --no-cache ca-certificates
COPY --from=builder /mosdns /usr/bin/mosdns
ENTRYPOINT ["/usr/bin/mosdns"]
